In [38]:
import tensorflow as tf
import numpy as np
from functools import partial
import pandas as pd

In [39]:
df = pd.read_csv('synthetic_dataset.csv')

In [45]:
dfgrp = df.groupby('LabelEmbeddingId')

batch = dfgrp.get_group(1)
batch

EmbeddingId  LastSessionEvent  SessionChanged  UserId  SessionId  \
0            0                 0               1       0          0   
1            0                 0               1       1          1   
2            0                 0               1       2          2   
3            0                 0               1       3          3   
4            0                 0               1       4          4   
5            0                 0               1       5          5   
6            0                 0               1       6          6   
7            0                 0               1       7          7   
8            0                 0               1       8          8   
9            0                 0               1       9          9   

   LabelEmbeddingId  
0                 1  
1                 1  
2                 1  
3                 1  
4                 1  
5                 1  
6                 1  
7                 1  
8                 1  
9                 1

In [62]:
sess = tf.Session()
labels = tf.constant([1,1,1,1,1,1,1,1,1,1])
logits = tf.constant([[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0],[0,1,0,0,0,0,0,0,0,0]])
logits = tf.cast(logits, tf.float32)
onehot_labels=tf.one_hot(indices=labels,depth=10)
loss = tf.nn.sparse_softmax_cross_entropy_with_logits(
                logits=logits,
                labels=labels)

probabilities = tf.nn.softmax(logits=logits)
    # cross entropy
loss_2 = -tf.reduce_sum(onehot_labels * tf.log(probabilities)) / tf.cast(tf.shape(labels)[0], tf.float32)

print(loss.eval(session=sess))
print(probabilities.eval(session=sess))
print(loss_2.eval(session=sess))
print(onehot_labels.eval(session=sess))

[1.4611502 1.4611502 1.4611502 1.4611502 1.4611502 1.4611502 1.4611502
 1.4611502 1.4611502 1.4611502]
[[0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 0.08533674 0.08533674]
 [0.08533674 0.23196931 0.08533674 0.08533674 0.08533674 0.08533674
  0.08533674 0.08533674 

In [3]:
tf.enable_eager_execution()

In [51]:
sess = tf.Session()
labels = tf.constant([9,9,9,9,9,9,9,9,9,9])
predictions = tf.constant([[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0],[0,0,0,0,0,0,0,0,0,0], [0,0,0,0,0,0,0,0,0,0] ])
_, pred_embedding_ids = tf.nn.top_k(predictions, 3)

labels_b = tf.broadcast_to(
            tf.expand_dims(labels, 1),
            tf.shape(pred_embedding_ids))

equals = tf.equal(pred_embedding_ids, labels_b)

ranked_indices = tf.where(equals)[:,1]

inverse_rank = 1/(ranked_indices + 1)

num_paddings = tf.shape(labels)[0] - tf.shape(inverse_rank)[0]

padded_inverse_rank = tf.pad(inverse_rank, [[num_paddings,0]])

print(labels.eval(session=sess))
print(labels.shape)
print(predictions.eval(session=sess))
print(predictions.shape)
print(pred_embedding_ids.eval(session=sess))
print(pred_embedding_ids.shape)
print(labels_b.eval(session=sess))
print(labels_b.shape)
print(equals.eval(session=sess))
print(equals.shape)
print(ranked_indices.eval(session=sess))
print(inverse_rank.eval(session=sess))
print(inverse_rank.eval(session=sess).shape)
print(num_paddings.eval(session=sess))
print(padded_inverse_rank.eval(session=sess))

[9 9 9 9 9 9 9 9 9 9]
(10,)
[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
(10, 10)
[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]]
(10, 3)
[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
(10, 3)
[[False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]
 [False False False]]
(10, 3)
[]
[]
(0,)
10
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [45]:
sess = tf.Session()
labels = tf.constant([0, 2, 4, 6, 8])
# b = tf.constant([2, 4, 6, 8])
matrix = tf.constant(np.random.normal(size=(5, 10)))
sampled = tf.gather(matrix, labels, axis=1)
# c = tf.meshgrid(a, a, indexing='ij')
# d = tf.stack(c, axis=-1)
# indices = tf.reshape(d, (-1,2))
# sampled = tf.gather_nd(matrix, indices)
# reshaped = tf.reshape(sampled, (tf.cast(tf.sqrt(tf.cast(tf.shape(indices)[0], tf.float32)), tf.int32),-1))
# trues = tf.cast(tf.ones(tf.shape(indices)[0]), tf.bool)

# mask = tf.sparse.to_dense(tf.sparse.SparseTensor(indices=tf.cast(indices, tf.int64), values=trues, dense_shape=tf.cast(tf.shape(matrix), tf.int64)), default_value=False)

# sampled = tf.boolean_mask(matrix, mask)
print(matrix.eval(session=sess))
print(sampled.eval(session=sess))
# print(c[0].eval(session=sess))
# print(c[1].eval(session=sess))
# print(d.eval(session=sess))
# print(indices.eval(session=sess))
# print(trues.eval(session=sess))
# print(mask.eval(session=sess))
# print(sampled.eval(session=sess))
# print(reshaped.eval(session=sess))

[[-0.54534566  1.05391914 -2.14473999 -0.6540254   0.61813964 -0.41913189
   1.37025418 -2.41976936 -2.287122    0.48093422]
 [-0.28184982  1.07988093 -1.2264055   0.62938774  1.74222185 -2.7207243
   1.19337708  0.44335918 -1.26571436  1.69747309]
 [ 0.17894494 -2.11649059  0.88012416  1.2509351   1.27272749 -1.28569436
   0.00441136 -1.24686603 -1.69613765 -0.61448814]
 [ 0.15712605  0.273392    0.27545426  0.16469995 -1.17576064  0.70824814
  -0.4215301  -0.35273834 -0.52482431 -0.63102204]
 [-1.89528472  1.65219233  0.89628062 -0.36504661  1.32336745 -0.1100085
  -2.02565581 -0.62732482 -1.45063266  0.91996485]]
[[-0.54534566 -2.14473999  0.61813964  1.37025418 -2.287122  ]
 [-0.28184982 -1.2264055   1.74222185  1.19337708 -1.26571436]
 [ 0.17894494  0.88012416  1.27272749  0.00441136 -1.69613765]
 [ 0.15712605  0.27545426 -1.17576064 -0.4215301  -0.52482431]
 [-1.89528472  0.89628062  1.32336745 -2.02565581 -1.45063266]]


In [14]:
a = tf.constant([1, 2, 3, 4])
b = tf.constant([5, 6, 7, 8])
tile_a = tf.tile(tf.expand_dims(a, 1), [1, tf.shape(b)[0]])  
tile_a = tf.expand_dims(tile_a, 2) 
tile_b = tf.tile(tf.expand_dims(b, 0), [tf.shape(a)[0], 1]) 
tile_b = tf.expand_dims(tile_b, 2) 

cartesian_product = tf.concat([tile_a, tile_b], axis=2) 
cartesian_product = tf.reshape(cartesian_product, (2,16))
cart = tf.Session().run(cartesian_product) 

print(cart.shape) 
print(cart) 

(2, 16)
[[1 5 1 6 1 7 1 8 2 5 2 6 2 7 2 8]
 [3 5 3 6 3 7 3 8 4 5 4 6 4 7 4 8]]


In [25]:
a = tf.constant([1, 0, 1, 0])
b = tf.constant([1, 2, 3, 4])
c = {
    1: [0.3,0.1,0.2],
    3: [0.4,0.6,0.5]
}

In [17]:
indices_to_update = tf.squeeze(
        tf.where(
            tf.cast(a, tf.bool),
            name='get_indices_to_update'
        ),
        axis=1
    )

indices_to_update

<tf.Tensor: id=45, shape=(2,), dtype=int64, numpy=array([0, 2])>

In [18]:
session_ids_to_update = tf.gather(b, indices_to_update)
session_ids_to_update

<tf.Tensor: id=48, shape=(2,), dtype=int32, numpy=array([1, 3], dtype=int32)>

In [23]:
session_ids_to_update.numpy()[0]

1

In [26]:
session_hidden_states = [c[x] for x in session_ids_to_update.numpy()]
session_hidden_states

[[0.3, 0.1, 0.2], [0.4, 0.6, 0.5]]

In [120]:
def get_or_initialize_embedding(embeddings, embedding_size, idx):
    idx = idx.numpy()
    if idx not in embeddings:
        embeddings[idx] = tf.random.normal((embedding_size,))
    return embeddings[idx]

def update_embedding(embeddings, embeddings_and_indices):
    embeddings[embeddings_and_indices[0]] = embeddings_and_indices[1]

a = dict()

getter = partial(get_or_initialize_embedding, a, 2)
setter = partial(update_embedding, a)

In [136]:
c = tf.constant([1,2,3])
d = tf.map_fn(getter, c, dtype=tf.float32)
d

<tf.Tensor: id=2907, shape=(3, 2), dtype=float32, numpy=
array([[ 0.21877675, -0.21164195],
       [-1.4698175 , -0.6282503 ],
       [ 0.8432651 , -0.4854022 ]], dtype=float32)>

In [138]:
e = tf.constant([[0.0,0.1], [0.0,0.1],[0.0,0.1]])
f = tf.map_fn(setter, tf.tuple(c,e))
a

tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
2
tf.Tensor(
[[0.  0.1]
 [0.  0.1]
 [0.  0.1]], shape=(3, 2), dtype=float32)
tf.Tensor([0.  0.1], shape=(2,), dtype=float32)


ValueError: Attempt to convert a value (None) with an unsupported type (<class 'NoneType'>) to a Tensor.